#!/bin/sh

SELECTION=$(tmux ls | gum filter | awk '{print $1}')
[[ -z $SELECTION ]] && echo 'nothing seleected' && exit 0
[[ -z $TMUX ]] && tmux attach-session -t $SELECTION && exit 0
tmux switch-client -t $SELECTION
